#!/system/bin/sh
if [ "`whoami`" != "root" ]
then su -c "$0"; exit
fi

(set -e
c=/sys/devices/system/cpu
if [ "`cat $c/cpu0/cpufreq/scaling_governor`" = performance ]
then
	echo freelunch > $c/cpu0/cpufreq/scaling_governor
	echo "Benchmarking Mode: OFF"
else
	echo performance > $c/cpu0/cpufreq/scaling_governor
	stop mpdecision
	echo 1 >$c/cpu1/online
	echo "Benchmarking Mode: ON"
fi) || echo "Error toggling Benchmarking Mode!"
